/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class NativeDemo */

#ifndef _Included_NativeDemo
#define _Included_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif

    JNIEXPORT void JNICALL Java_com_gobigg_cloud_common_util_iot_DspLib_fft(JNIEnv*, jobject, jdoubleArray);

    JNIEXPORT void JNICALL Java_com_gobigg_cloud_common_util_iot_DspLib_accToVel(JNIEnv*, jobject, jdoubleArray, jdouble, jdouble, jdouble, jdoubleArray);

    JNIEXPORT void JNICALL Java_com_gobigg_cloud_common_util_iot_DspLib_rceps(JNIEnv*, jobject, jdoubleArray input);

    JNIEXPORT jdoubleArray JNICALL Java_com_gobigg_cloud_common_util_iot_DspLib_dmcalc(JNIEnv*, jobject,
        jdoubleArray, jfloat, jdouble, jdouble, jdouble, jfloat);

#ifdef __cplusplus
}
#endif
#endif
